[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "advent-of-visualizations"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = ["textual>=6.7.1"]

[dependency-groups]
dev = ["ruff>=0.14.6"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "UP",
    "D",
    "INP",
    "S",
    "PLR",
    "F",
    "FIX",
    "TC",
    "FBT",
    "RUF",
    "E",
    "B",
]

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]

[tool.pyright]
ignore = ["**/__init__.py"]
typeCheckingMode = "standard"
